### ISSUE TITLE
Bottom Overlay disappears even though 'false'

### ISSUE THREAD

**Issue by hpbaum** [mroter93/TeamsHider#3]
Great addon to Teams, to fix MS shortcomings. Thanks a bunch.
If possible to tweak one tiny bit...
My setting.conf file :
{
	HideTopBar: true,
	HideBottomOverlay: false
}
The top bar does not appear anymore. Hooray!
As for the BottomOverlay (with the videos of the meeting participants), it gets reduced to a mini window each time a local 'Share' action is started, then gets reduced to the tray, from where I must reopen and resize it (in order to see everybody again).
It be great, whenever you can make the time...
Cheers,
    H.-P.

**Comment by mroter93** [comment]
Thank you for the report. I will fix it in the upcoming days if I can reproduce it locally.

**Comment by mroter93** [comment]
Fixed in v4 :)
